version: '3.8'

services:
  agentic_bench:
    build:
      context: ./agentic_bench
      dockerfile: Dockerfile
    volumes:
      - ./agentic_bench:/app
    env_file:
      - .env
    restart: always
    # ports:
    #   - "8081:8081"
    network_mode: host

  agentic_browser:
    build:
      context: ./TheAgenticBrowser
      dockerfile: Dockerfile
    volumes:
      - ./TheAgenticBrowser:/app
    env_file:
      - .env
    restart: always
    # ports:
    #   - "8000:8000"
    network_mode: host
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - agentic_bench
      - agentic_browser
    restart: always
    # ports:
    #   - "3000:3000"
    network_mode: host